Implement SignUpVC
irina-gs/todo pull request #1
Opened 2023-11-07 10:08 UTC by irina-gs

2023-11-08 22:25 UTC, tepaevayuliya commented on todo/Classes/Modules/SignUp/SignUpViewController.swift
> +    @IBOutlet weak var passwordTextField: TextInput!
Переменные usernameTextField, emailTextField и passwordTextField должны быть private

2023-11-08 22:30 UTC, tepaevayuliya commented on todo/Classes/Modules/SignUp/SignUpViewController.swift
> +        passwordTextField.enableSecurityMode()
По дизайну на странице «Регистрация» не должно быть иконки глаза в поле ввода пароля

2023-11-08 22:31 UTC, tepaevayuliya commented on todo/Classes/Modules/SignUp/SignUpViewController.swift
> +    }
Отсутствует label с ошибкой «Поле должно быть заполнено» под полем «Имя пользователя»

2023-11-08 22:37 UTC, tepaevayuliya commented on todo/Resources/Storyboards/SignUp.storyboard
> +                            <constraint firstItem="SL7-3v-khX" firstAttribute="bottom" secondItem="svF-z5-fdl" secondAttribute="bottom" id="dxw-pg-8xI"/>
Нижний отступ должен быть равен Stack View.bottom + 16, а не просто Stack View.bottom (по факту должно быть так: <constraint firstItem="SL7-3v-khX" firstAttribute="bottom" secondItem="svF-z5-fdl" secondAttribute="bottom" constant="16" id="dxw-pg-8xI"/>)

2023-11-09 14:15 UTC, aps21 requested changes

2023-11-09 14:15 UTC, aps21 commented on todo/Classes/Modules/Auth/AuthViewController.swift
> +
лишняя пустая строка

2023-11-09 14:15 UTC, aps21 commented on todo/Classes/Modules/Auth/AuthViewController.swift
> +        navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
молодец, неплохо))
потом мы сделаем viewController.navigationItem.backButtonDisplayMode = .minimal

2023-11-09 14:15 UTC, aps21 commented on todo/Classes/Modules/SignUp/SignUpViewController.swift
> +
лишняя пустая строка

2023-11-09 14:15 UTC, aps21 commented on todo/Classes/Modules/SignUp/SignUpViewController.swift
> +    @IBOutlet weak var passwordTextField: TextInput!
аутлеты должны быть приватными и strong (если соединяешь через ксиб/сториборд)
@IBOutlet private var usernameTextField: TextInput!

2023-11-09 14:15 UTC, aps21 commented on todo/Classes/Modules/SignUp/SignUpViewController.swift
> +        view.window?.rootViewController = vc
🔥

2023-11-09 14:15 UTC, aps21 commented on todo.xcodeproj/project.pbxproj
> +		843090E52AF90B590098BEC6 /* SignUpViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 843090E42AF90B590098BEC6 /* SignUpViewController.swift */; };
в этой ветке не хватает файла UIViewController+Keyboard.swift

2023-11-09 14:15 UTC, aps21 commented on todo.xcodeproj/project.pbxproj
> +		843090E52AF90B590098BEC6 /* SignUpViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 843090E42AF90B590098BEC6 /* SignUpViewController.swift */; };
на следующий урок будет валидация

2023-11-09 21:14 UTC, merged