Add custom button and validation
irina-gs/todo pull request #2
Opened 2023-11-14 09:48 UTC by irina-gs

2023-11-16 06:45 UTC, Boslana requested changes

2023-11-16 06:45 UTC, Boslana commented on todo/UIKit/PrimaryButton.swift
> +                insets: 256,
неверное значение, надо 44

2023-11-16 06:45 UTC, Boslana commented on todo/UIKit/TextButton.swift
> +                insets: 218,
insets не нужны

2023-11-16 06:45 UTC, Boslana commented on todo/UIKit/TextButton.swift
> +                insets: 320,
insets не нужны

2023-11-16 10:54 UTC, aps21 requested changes

2023-11-16 10:54 UTC, aps21 commented on todo/Classes/Business/ValidationManager.swift
> +        (commonText ?? "").count != 0
убери комменты в static func isValid(commonText: String?, symbolsCount: Int) -> Bool

2023-11-16 10:54 UTC, aps21 commented on todo/Classes/Business/ValidationManager.swift
> +        (commonText ?? "").count != 0
вместо этой функции можно передавать дефолтный аргумент в static func isValid(commonText: String?, symbolsCount: Int = 0) -> Bool

2023-11-16 10:54 UTC, aps21 commented on todo/UIKit/PrimaryButton.swift
> +                insets: 256,
давай по 32

2023-11-16 10:54 UTC, aps21 commented on todo/UIKit/TextButton.swift
> +                insets: 218,
думаю, что слишком большие инсеты, давай сделаем 32

2023-11-16 10:54 UTC, aps21 commented on todo/UIKit/TextButton.swift
> +                height: 22,
22 - слишком мало, чтоб юзер смог нажать, давай сделаем 54

2023-11-16 13:19 UTC, irina-gs commented on todo/UIKit/PrimaryButton.swift
> +                insets: 256,
В фирме стоят по 22. Может тогда правильнее 44 сделать?

2023-11-16 13:32 UTC, irina-gs commented on todo/UIKit/TextButton.swift
> +                height: 22,
Тогда spacing у стека с кнопками лучше выставить в 0 или оставить 16?

2023-11-17 09:31 UTC, aps21 commented on todo/UIKit/TextButton.swift
> +                height: 22,
в ноль, верстка не должна сильно отличаться от дизов)

2023-11-17 09:31 UTC, aps21 commented on todo/UIKit/PrimaryButton.swift
> +                insets: 256,
да, ты права

2023-11-18 19:07 UTC, merged