MainItemCell and ErrorVC
irina-gs/todo pull request #4
Opened 2023-11-19 11:58 UTC by irina-gs

2023-11-21 17:00 UTC, tepaevayuliya commented on todo/Classes/Modules/Empty/EmptyViewController.swift
> +        emptyLabel.font = .systemFont(ofSize: 18, weight: .bold)
По дизайну тут полужирный шрифт: emptyLabel.font = .systemFont(ofSize: 18, weight: .semibold)

2023-11-21 17:00 UTC, tepaevayuliya commented on todo/Classes/Modules/Empty/EmptyViewController.swift
> +    @IBAction private func didTapUpdateButton() {
Возможно в эту функцию нужно добавить обновление статуса, так как иначе может получиться ситуация как на видео, что пользователь может вернуться с MainVC к EmptyVC и снова увидеть ту же самую ошибку

https://github.com/irina-gs/todo/assets/57157605/1e802e91-aead-44c3-b2c6-9b6ae4365baf

2023-11-21 17:00 UTC, tepaevayuliya commented on todo/Classes/Modules/Empty/EmptyViewController.swift
> +            updateButton.isHidden = true
Сюда нужно еще добавить emptyButton.isHidden = false, чтобы в случае обновления статуса пользователю показывалась нужная кнопка

https://github.com/irina-gs/todo/assets/57157605/373d9d78-7e4d-40fc-a347-e8d882d27d61

2023-11-21 17:00 UTC, tepaevayuliya commented on todo/Classes/Modules/Empty/EmptyViewController.swift
> +                emptyButton.isHidden = true
Тут ситуация как и в случае выше: updateButton.isHidden = false

2023-11-21 17:00 UTC, tepaevayuliya commented on todo/Classes/Modules/Main/Cell/MainItemCell.swift
>      private func updateColor() {
Возможно стоит переименовать функцию, так как сейчас там обновляется картинка, а не цвет

2023-11-21 17:00 UTC, tepaevayuliya commented on todo/Classes/Modules/Main/Cell/MainItemCell.swift
> +            alpha = isHighlighted ? 0.5 : 1
Возможно стоит ставить альфу не для всего item, а конкретно для фона, чтобы этот параметр не применялся к лейблам

https://github.com/irina-gs/todo/assets/57157605/d70b467c-cb1b-42f0-9e34-7c66f5eebe28

2023-11-21 17:29 UTC, tepaevayuliya commented on todo/Classes/Modules/Main/Cell/MainItemCell.xib
![image](https://github.com/irina-gs/todo/assets/57157605/49757335-aa18-49ed-84f5-ff37860c7aba)
Добавить leading, trailing

2023-11-22 17:02 UTC, Boslana requested changes

2023-11-22 17:02 UTC, Boslana commented on todo/Classes/Modules/Empty/EmptyViewController.swift
> +            switch error {
повторяющиеся строчки (emptyButton.isHidden = true, updateButton.setTitle(L10n.Main.errorUpdateButton, for: .normal), updateButton.setMode(mode: .small)) можно вынести, что бы они не дублировались

2023-11-22 17:02 UTC, Boslana commented on todo/Classes/Modules/Empty/EmptyViewController.swift
> +        action?()
открывается экран создания новой записи

2023-11-23 18:13 UTC, aps21 commented on todo/Classes/Modules/Empty/EmptyViewController.swift
> +        state = .empty
надо будет потом переделать на кложуры
у пустого состояния - переход на создание нового дела
у ошибки - сделать снова запрос на список дел

2023-11-23 18:13 UTC, aps21 commented on todo/Classes/Modules/Main/Cell/MainItemCell.swift
> +            alpha = isHighlighted ? 0.5 : 1
без разницы, я в тз этого не указала)

2023-11-23 18:13 UTC, aps21 commented on todo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        dateFormatter.dateFormat = L10n.Main.dateFormat
вынеси в отдельную переменную, чтоб он у тебя не создавался каждый раз заново
можно lazy var, но в идеале лучше сделать в отдельном файле
```
extension DateFormatter { 
static let `default` = {
 let formatter = ...
 ... 
 return formatter
 }()
}
```

2023-11-23 18:13 UTC, aps21 commented on todo/Classes/Modules/Main/Cell/MainItemCell.xib
> +                                            <constraint firstAttribute="height" constant="24" id="fe5-p6-hIa"/>
лишний констрейнт на высоту у titleLabel - у тебя уже есть констрейнты у картинки, их хватит

2023-11-23 18:13 UTC, aps21 commented on todo/Classes/Modules/Main/Cell/MainItemCell.xib
> +                            <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Label" textAlignment="natural" lineBr
сделай хотя бы 2 линии (Lines) - теоретически может не влезть на маленьких девайсах

2023-11-26 21:43 UTC, merged