EditItem
irina-gs/todo pull request #6
Opened 2023-12-04 22:23 UTC by irina-gs

2023-12-05 17:24 UTC, Boslana requested changes

2023-12-05 17:24 UTC, Boslana commented on todo/Classes/Modules/Main/Cell/MainItemCell.xib
можно добавить spacing между текстом и радиокнопкой, сейчас почти в плотную )
<img width="343" alt="Screenshot at Dec 05 19-40-33" src="https://github.com/irina-gs/todo/assets/88737219/ec135f29-1849-4786-a7ea-08c88c30c4ba">

2023-12-05 17:24 UTC, Boslana commented on todo/Classes/Modules/Main/MainViewController.swift
> +                        cell.setMark(isCompleted: self!.data[indexPath.row].isCompleted)
Force unwrapping не хорошо) можно использовать if let или guard let

2023-12-05 17:24 UTC, Boslana commented on todo/Classes/Modules/NewItem/NewItemViewController.swift
На экране редактирования при открытой клавиатуре есть лишний отступ и при закрытой клавиатуре большой отступ снизу, возможно стоит добавить еще одну констрейнту и деактивировать ее 
<img width="349" alt="Screenshot at Dec 05 20-12-47" src="https://github.com/irina-gs/todo/assets/88737219/20c5b721-bc0f-4acc-88eb-c4f54903c618">

2023-12-05 18:53 UTC, tepaevayuliya commented on todo/Classes/Modules/NewItem/NewItemViewController.swift
Лучше ещё включать/отключать констрейнты на высоту скроллвью, чтобы не было белой полосы снизу, где у нас была кнопка создания записи
<img width="320" alt="image" src="https://github.com/irina-gs/todo/assets/57157605/d145cced-605b-4b85-9633-a5031eba27b8">
<img width="311" alt="image" src="https://github.com/irina-gs/todo/assets/57157605/291f7ed9-caff-42ff-8cef-d2ed365f2d04">

2023-12-05 18:53 UTC, tepaevayuliya commented on todo/Classes/Modules/Main/MainViewController.swift
<img width="306" alt="image" src="https://github.com/irina-gs/todo/assets/57157605/fa212e3a-a74e-43d2-ac2b-83c080fd07d5">
Можно убрать тут верхний констрейнт на 16 у кнопки

2023-12-05 18:53 UTC, tepaevayuliya commented on todo/Classes/Modules/Main/MainViewController.swift
> +                        cell.setMark(isCompleted: self!.data[indexPath.row].isCompleted)
Лучше не использовать force unwrap

2023-12-05 18:53 UTC, tepaevayuliya commented on todo/UIKit/StatefullView.swift
> +        emptyView.isHidden = true
о, точно)
кажется, надо у себя тоже добавить это🙂

2023-12-06 10:34 UTC, aps21 commented on todo/Classes/Modules/NewItem/NewItemViewController.swift
мб на высоту кнопки? @tepaevayuliya

2023-12-06 10:56 UTC, aps21 requested changes

2023-12-06 10:56 UTC, aps21 commented on todo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        markButton.setTitle("", for: .normal)
этот код у тебя никак не зависит от item, вынеси его из этой функции, например, в awakeFromNib

2023-12-06 10:56 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +                        cell.setMark(isCompleted: self!.data[indexPath.row].isCompleted)
итак, добро пожаловать в увлекательный мир реюза ячеек))
кейс:
в 112 строке написать try? await Task.sleep(for: .seconds(3))
все дела сделать невыполненными
тыкнуть первое дело выполненным
быстро проскроллить в самый низ
подождать 3 секунды
поскроллить наверх
скорее всего ты заметишь, что у тебя не только первое дело выполнено, но и еще какое-то
при этом если поскроллить еще разок, то всё будет ок
подниму тему на занятии, пинай, если вдруг забуду

2023-12-06 10:56 UTC, aps21 commented on todo/Classes/Modules/NewItem/NewItemViewController.swift
> +
лишняя пустая строка

2023-12-06 10:56 UTC, aps21 commented on todo/Classes/Modules/NewItem/NewItemViewController.swift
> +                _ = try await NetworkManager.shared.deleteTodo(id: selectedItem?.id ?? "")
в теории можно заменить на 
```
guard let selectedItem else {
    return
}
```

2023-12-06 10:56 UTC, aps21 commented on todo/UIKit/StatefullView.swift
> +                subview.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -32),
у тебя сейчас пустое состояние выровнено относительно супервью, давай поправим, чтоб верх/низ был прикреплен к safeAreaLayoutGuide
```
[emptyView, loaderView].forEach { subview in
    NSLayoutConstraint.activate([
        subview.leadingAnchor.constraint(equalTo: leadingAnchor),
        subview.topAnchor.constraint(equalTo: safeAreaLayoutGuide.topAnchor),
        subview.trailingAnchor.constraint(equalTo: trailingAnchor),
        subview.bottomAnchor.constraint(equalTo: safeAreaLayoutGuide.bottomAnchor),
    ])
}
```

2023-12-06 11:00 UTC, aps21 commented
убери закомментированный enum CustomError: Error { ...

2023-12-06 11:01 UTC, aps21 commented on todo/Classes/Modules/Main/Cell/MainItemCell.xib
> +                                            <constraint firstAttribute="height" constant="24" id="llj-WO-mvH"/>
на занятии расскажу про 44х44

2023-12-07 13:57 UTC, merged