ProfileVC and SnackBarView
irina-gs/todo pull request #7
Opened 2023-12-11 23:55 UTC by irina-gs

2023-12-12 12:34 UTC, Boslana requested changes

2023-12-12 12:34 UTC, Boslana commented on todo/Network/Responses/UserResponse.swift
> +    let email: String
можно убрать email, вроде его не используем

2023-12-12 12:34 UTC, Boslana commented on todo/UIKit/SnackBarView.swift
> +        massageLabel.text = massage
m**e**ssage)

2023-12-12 12:34 UTC, Boslana commented on todo/UIKit/SnackBarView.swift
> +            massageLabel.trailingAnchor.constraint(equalTo: trailingAnchor),
надо добавить по 16 точек справа и слева

2023-12-12 12:34 UTC, Boslana commented on todo/UIKit/SnackBarView.swift
> +        view.addSubview(self)
сейчас снек бар отображается под навбаром, виднеются кнопки. можно добавить на window

2023-12-12 12:34 UTC, Boslana commented on todo/Extensions/DateFormatter.swift
> +        let formatter = DateFormatter()
можно добавить русскую локализацию

2023-12-12 12:34 UTC, Boslana commented on todo/Classes/Modules/Profile/ProfileViewController.swift
> +                usernameLabel.text = user?.name
возможно стоит обернуть в DispatchQueue.main.async

2023-12-12 12:34 UTC, Boslana commented on todo/Classes/Modules/Profile/ProfileViewController.swift
> +        alertVC.addAction(UIAlertAction(title: L10n.Profile.alertCanselButton, style: .cancel))
Cancel )

2023-12-12 12:34 UTC, Boslana commented on todo/Classes/Modules/Main/MainViewController.swift
struct MainDataItem можно вынести в отдельный файлик в папку Network как остальные )

2023-12-13 15:09 UTC, tepaevayuliya commented on todo/Classes/Modules/Parent/ParentViewController.swift
> +        snackBar.setupMassage(massage: L10n.SnackBar.massage)
Возможно стоит добавить разные типы ошибок, как у нас было в алерте (хотя по дизайну всё так, как у тебя🙂)

2023-12-13 15:09 UTC, tepaevayuliya commented on todo/UIKit/SnackBarView.swift
> +                        self.frame = CGRect(x: 0, y: -height, width: view.frame.size.width, height: height)
CGRect(x: 0, y: -height, width: view.frame.size.width, height: height) – дублировние кода в строках 51, 61

2023-12-13 15:09 UTC, tepaevayuliya commented on todo/UIKit/SnackBarView.swift
> +            massageLabel.topAnchor.constraint(equalTo: topAnchor, constant: 50),
Возможно стоит привязать константу к высоте статус бара, он вроде бы на разных девайсах немного отличается по высоте

2023-12-13 15:22 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +        performSegue(withIdentifier: "profile", sender: nil)
🔥

2023-12-13 15:22 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +                if (error as NSError).code == 401 {
в идеале вынести в одно место))
использовать будем везде
и в request(...) надо отдельно тогда обрабатывать 401 :(
сейчас не сработает
плюс у тебя сейчас если нет аксесстокена для некоторых запросов, то выкидывается NetworkError.wrongStatusCode, надо этот момент тоже доработать

как проверить - запиши accessToken = "", запусти прилу

2023-12-13 15:22 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +                if DateFormatter.year.string(from: dateCell) == DateFormatter.year.string(from: Date()) {
Calendar.current.isDate(<#T##date1: Date##Date#>, equalTo: <#T##Date#>, toGranularity: .year)

2023-12-13 15:22 UTC, aps21 commented on todo/Classes/Modules/Profile/ProfileViewController.swift
> +                usernameLabel.text = user?.name
в общем необязательно
пока сиреневеньким не ругается, всё ок

2023-12-14 10:44 UTC, merged