ImagePicker and multipartFormData
irina-gs/todo pull request #8
Opened 2023-12-19 08:08 UTC by irina-gs

2023-12-19 18:57 UTC, Boslana requested changes

2023-12-19 18:57 UTC, Boslana commented on todo/Classes/Modules/Main/MainViewController.swift
> +    func didSelect(_: NewItemViewController, newItemData: MainDataItem) {
если выбрать дату и создать запись на другую дату, то скроллит вниз, но там записи нет. можно попробовать убрать скролл в таком случае) 

https://github.com/irina-gs/todo/assets/88737219/e72c9f48-e380-4c47-8f1c-7904603d2ce3

2023-12-19 18:57 UTC, Boslana commented on todo/Classes/Modules/Main/MainViewController.swift
при обновлении экрана с помощью PTR, refreshControl отображается не на все время пока идет запрос, а сразу исчезает 

https://github.com/irina-gs/todo/assets/88737219/47d78706-07c2-4ec5-81f9-c37e5d879771

2023-12-19 18:57 UTC, Boslana commented on todo/Classes/Modules/Profile/ProfileViewController.swift
usernameLabel можно исправить на userNameLabel )

2023-12-19 18:57 UTC, Boslana commented on todo/Extensions/Data+.swift
возможно можно переименовать файл во что нибудь типо Data+AppendString, что бы было сразу понятно)

2023-12-19 19:07 UTC, Boslana requested changes

2023-12-19 19:07 UTC, Boslana commented on todo/UIKit/Button/PrimaryButton.swift
> +            addSubview(loader)
лоадер будет каждый раз добавляться при вызове функции

2023-12-20 17:30 UTC, tepaevayuliya commented on todo/Classes/Modules/Profile/ProfileViewController.swift
Возможно стоит масштабировать картинку, если она не квадратная, чтобы не было обрезано по бокам или сверху/снизу
![image](https://github.com/irina-gs/todo/assets/57157605/714e23d3-51c6-4610-8491-0c74a8eccf1e)
![image](https://github.com/irina-gs/todo/assets/57157605/e72bd3b1-8284-457d-81cd-6b3b4d3c620d)

2023-12-22 15:04 UTC, aps21 requested changes

2023-12-22 15:04 UTC, aps21 commented on todo/.DS_Store
лишний?

2023-12-22 15:04 UTC, aps21 commented on todo/Classes/Business/Factories/ManagersAssembly.swift
> +        }
можно сократить до
```
container.register { NetworkManager(decoder: $0, encoder: $1) }
            .implements(AuthManager.self)
            .implements(SignUpManager.self)
            .implements(MainManager.self)
            .implements(NewItemManager.self)
            .implements(ProfileManager.self)
```

2023-12-22 15:04 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +        }
можно через collectionView.numberOfItems in section

2023-12-22 15:04 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +        if data.isEmpty {
❤️

2023-12-22 15:04 UTC, aps21 commented on todo/Classes/Modules/Profile/ProfileViewController.swift
> +                    _ = try await self?.networkManager.uploadUserPhoto(image: image)
пока идет загрузка - нет никакой индикации
с точки зрения пользователя - непонятно, можно ли уходить с экрана или что-то еще идет

2023-12-22 15:04 UTC, aps21 commented on todo/Extensions/Data+.swift
вкусовщина: по-разному на разных проектах
где-то, символ + значит, что тут будут экстеншены у данного типа
где-то надо делать экстеншены в разных файликах по их назначению, и тогда уже называть каждый нормально

2023-12-22 15:04 UTC, aps21 commented on todo/UIKit/Button/PrimaryButton.swift
> +        titleLabel?.isHidden = true
еще надо прятать картиночку, если вдруг она есть
но это скорее придирка

2023-12-22 15:04 UTC, aps21 commented on todo/Manager/ProfileManager.swift
> +            throw NetworkError.wrongStatusCode
давай другую ошибку, чтоб юзер понял, что его фотка слишком огромна

2023-12-22 15:04 UTC, aps21 commented on todo/UIKit/ImagePicker/ImagePicker.swift
> +    var imagePickerController: UIImagePickerController?
private?

2023-12-22 15:04 UTC, aps21 commented on todo/UIKit/ImagePicker/ImagePicker.swift
> +        imagePickerController?.mediaTypes = ["public.image"]
❤️

2023-12-22 15:04 UTC, aps21 commented on todo/UIKit/SnackBar/SnackBarView.swift
> +
давай у лейбла top к статус бару + 6, а то слишком прижат на se

2023-12-25 08:20 UTC, merged